apiVersion: v1
kind: Service
metadata:
 name: nginx-service
spec:
   type: LoadBalancer
   externalIPs:
   - x.x.x.x
   selector:
        app: nginx
        version: "1.0"
   ports:
        - port: 8888
          targetPort: 80
          nodePort: 32762

